services:
  andes-fhir-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: andes-fhir-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
